name: Merge Files from Output to Main

on:
  # run automatically every day 23:55
  schedule:
    - cron: "57 23 * * *" 

jobs:
  copy_files:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Main Branch
      uses: actions/checkout@v2
      with:
        ref: main
        path: main

    - name: Checkout Output Branch
      uses: actions/checkout@v2
      with:
        ref: output
        path: output

    - name: Copy Files to Main Branch
      run: |
        mkdir -p main/res
        cp -r output/* main/res/

    - name: Commit and Push Changes to Main Branch
      run: |
        cd main
        git config --global user.email "2450854008@qq.com"
        git config --global user.name "Country-If"
        git add res/
        git commit -m "Automated copy of files from output to main/res" || true
        git push origin HEAD:main || true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # 使用GitHub提供的token进行身份验证
